objects = Monster.o Dragon.o Spirit.o Exoskeleton.o

Monster.o : Monster.cpp
	g++ -c Monster.cpp


Dragon.o : Dragon.cpp
	g++ -c Dragon.cpp


Spirit.o : Spirit.cpp
	g++ -c Spirit.cpp

Exoskeleton.o : Exoskeleton.cpp
	g++ -c Exoskeleton.cpp

.PHONY: clean

clean:
	rm $(objects)
